apiVersion: core.devicechain.io/v1beta1
kind: MicroserviceConfiguration
metadata:
  creationTimestamp: null
  name: event-sources-default
spec:
  configuration:
    EventSources:
    - Configuration:
        host: dc-mosquitto.dc-system
        port: "1883"
        topic: devicechain/events
      Debug: false
      Decoder:
        Configuration: {}
        Type: json
      Id: mqtt1
      Type: mqtt
    InboundEventBatching:
      BatchTimeoutMs: 100
      MaxBatchSize: 100
  functionalArea: event-sources
  image: devicechain-io/event-sources:0.0.1
status: {}
