apiVersion: core.devicechain.io/v1beta1
kind: InstanceConfiguration
metadata:
  creationTimestamp: null
  name: dcic-default
spec:
  configuration:
    Infrastructure:
      Kafka:
        DefaultTopicPartitions: 4
        DefaultTopicReplicationFactor: 1
        Hostname: dc-kafka-kafka-bootstrap.dc-system
        Port: 9092
      Keycloak:
        Hostname: dc-keycloak.dc-system
        Port: 8080
      Metrics:
        Enabled: true
        HttpPort: 9090
      Redis:
        Hostname: dc-redis-master.dc-system
        Port: 6379
    Persistence:
      Rdb:
        Configuration:
          hostname: dc-postgresql.dc-system
          maxConnections: 5
          password: devicechain
          port: 5432
          username: devicechain
        Type: postgres95
      Tsdb:
        Configuration:
          hostname: dc-timescaledb-single.dc-system
          maxConnections: 5
          password: devicechain
          port: 5432
          username: postgres
        Type: timescaledb
status: {}
