apiVersion: core.devicechain.io/v1beta1
kind: InstanceConfiguration
metadata:
  creationTimestamp: null
  name: dcic-default
spec:
  configuration:
    Infrastructure:
      Kafka:
        DefaultTopicPartitions: 8
        DefaultTopicReplicationFactor: 3
        Hostname: dc-kafka-kafka-bootstrap
        Port: 9092
      Keycloak:
        Hostname: dc-keycloak.dc-system
        Port: 8080
      Metrics:
        Enabled: true
        HttpPort: 9090
      Redis:
        Hostname: dc-redis-master.dc-system
        Port: 6379
    Persistence:
      Rdb:
        Configuration:
          hostname: dc-postgresql.dc-system
          maxConnections: 5
          password: devicechain
          port: 5432
          username: devicechain
        Type: postgres95
      Tsdb:
        Configuration:
          databaseName: tenant_${tenant.id}
          hostname: dc-influxdb.dc-system
          port: 8086
        Type: influxdb
status: {}
